apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: rag-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: chat-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: QUERY_SERVICE_URL
          value: "http://query-service.rag-system:8001"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 20