apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: rag-system
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP 
