apiVersion: v1
kind: Service
metadata:
  name: encode-service
  namespace: rag-system
spec:
  selector:
    app: encode-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP