apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode-service
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encode-service
  template:
    metadata:
      labels:
        app: encode-service
    spec:
      containers:
        - name: encode-service
          image: encode_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: EMBEDDINGS_FILE
              value: "/app/data/embeddings.json"
          volumeMounts:
            - name: rag-storage
              mountPath: /app/data
      volumes:
        - name: rag-storage
          persistentVolumeClaim:
            claimName: rag-pvc