apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encode-service
  template:
    metadata:
      labels:
        app: encode-service
    spec:
      containers:
        - name: encode-service
          image: encode_service:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: encode-service
spec:
  selector:
    app: encode-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  
