apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: rag-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: query-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: ENCODE_SERVICE_URL
              value: "http://encode-service.rag-system:8000"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"