apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: rag-system
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP