apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rag-system
spec:
  type: NodePort  # Changed from ClusterIP to NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # This will make the API accessible on port 30000