apiVersion: v1
kind: Service
metadata:
  name: composite-service
  namespace: rag-system
spec:
  selector:
    app: composite-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP