apiVersion: apps/v1
kind: Deployment
metadata:
  name: composite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composite-service
  template:
    metadata:
      labels:
        app: composite-service
    spec:
      containers:
      - name: composite-service
        image: composite_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        volumeMounts:
        - name: documents-volume
          mountPath: /app/documents
      volumes:
      - name: documents-volume
        hostPath:
          path: /path/to/your/documents
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: composite-service
spec:
  selector:
    app: composite-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP 